[package]
authors = ["Kristoffer Ström <kristoffer@ethcore.io>"]
name = "trie"
version = "0.1.0"

[dependencies]
byteorder = "0.5.3"
parking_lot = "0.3.5"
rand = "0.3.14"
trait-group = "0.1.0"

[dependencies.content]
path = "../content"
